// Mocks generated by Mockito 5.4.6 from annotations
// in ueberboese_app/test/main_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i9;

import 'package:mockito/mockito.dart' as _i1;
import 'package:ueberboese_app/models/bass.dart' as _i6;
import 'package:ueberboese_app/models/clock_display.dart' as _i7;
import 'package:ueberboese_app/models/now_playing.dart' as _i5;
import 'package:ueberboese_app/models/preset.dart' as _i11;
import 'package:ueberboese_app/models/recent.dart' as _i12;
import 'package:ueberboese_app/models/speaker.dart' as _i3;
import 'package:ueberboese_app/models/speaker_info.dart' as _i2;
import 'package:ueberboese_app/models/volume.dart' as _i4;
import 'package:ueberboese_app/models/zone.dart' as _i10;
import 'package:ueberboese_app/services/speaker_api_service.dart' as _i8;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeDuration_0 extends _i1.SmartFake implements Duration {
  _FakeDuration_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSpeakerInfo_1 extends _i1.SmartFake implements _i2.SpeakerInfo {
  _FakeSpeakerInfo_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSpeaker_2 extends _i1.SmartFake implements _i3.Speaker {
  _FakeSpeaker_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeVolume_3 extends _i1.SmartFake implements _i4.Volume {
  _FakeVolume_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeNowPlaying_4 extends _i1.SmartFake implements _i5.NowPlaying {
  _FakeNowPlaying_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeBassCapabilities_5 extends _i1.SmartFake
    implements _i6.BassCapabilities {
  _FakeBassCapabilities_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeBass_6 extends _i1.SmartFake implements _i6.Bass {
  _FakeBass_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeClockConfig_7 extends _i1.SmartFake implements _i7.ClockConfig {
  _FakeClockConfig_7(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [SpeakerApiService].
///
/// See the documentation for Mockito's code generation for more information.
class MockSpeakerApiService extends _i1.Mock implements _i8.SpeakerApiService {
  MockSpeakerApiService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  Duration get timeout =>
      (super.noSuchMethod(
            Invocation.getter(#timeout),
            returnValue: _FakeDuration_0(this, Invocation.getter(#timeout)),
          )
          as Duration);

  @override
  _i9.Future<_i2.SpeakerInfo> fetchSpeakerInfo(String? ipAddress) =>
      (super.noSuchMethod(
            Invocation.method(#fetchSpeakerInfo, [ipAddress]),
            returnValue: _i9.Future<_i2.SpeakerInfo>.value(
              _FakeSpeakerInfo_1(
                this,
                Invocation.method(#fetchSpeakerInfo, [ipAddress]),
              ),
            ),
          )
          as _i9.Future<_i2.SpeakerInfo>);

  @override
  _i9.Future<_i3.Speaker> createSpeakerFromIp(
    String? ipAddress,
    String? emoji,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#createSpeakerFromIp, [ipAddress, emoji]),
            returnValue: _i9.Future<_i3.Speaker>.value(
              _FakeSpeaker_2(
                this,
                Invocation.method(#createSpeakerFromIp, [ipAddress, emoji]),
              ),
            ),
          )
          as _i9.Future<_i3.Speaker>);

  @override
  _i9.Future<_i4.Volume> getVolume(String? ipAddress) =>
      (super.noSuchMethod(
            Invocation.method(#getVolume, [ipAddress]),
            returnValue: _i9.Future<_i4.Volume>.value(
              _FakeVolume_3(this, Invocation.method(#getVolume, [ipAddress])),
            ),
          )
          as _i9.Future<_i4.Volume>);

  @override
  _i9.Future<_i4.Volume> setVolume(String? ipAddress, int? volume) =>
      (super.noSuchMethod(
            Invocation.method(#setVolume, [ipAddress, volume]),
            returnValue: _i9.Future<_i4.Volume>.value(
              _FakeVolume_3(
                this,
                Invocation.method(#setVolume, [ipAddress, volume]),
              ),
            ),
          )
          as _i9.Future<_i4.Volume>);

  @override
  _i9.Future<_i5.NowPlaying> getNowPlaying(String? ipAddress) =>
      (super.noSuchMethod(
            Invocation.method(#getNowPlaying, [ipAddress]),
            returnValue: _i9.Future<_i5.NowPlaying>.value(
              _FakeNowPlaying_4(
                this,
                Invocation.method(#getNowPlaying, [ipAddress]),
              ),
            ),
          )
          as _i9.Future<_i5.NowPlaying>);

  @override
  _i9.Future<_i10.Zone?> getZone(String? ipAddress) =>
      (super.noSuchMethod(
            Invocation.method(#getZone, [ipAddress]),
            returnValue: _i9.Future<_i10.Zone?>.value(),
          )
          as _i9.Future<_i10.Zone?>);

  @override
  _i9.Future<void> createZone(
    String? ipAddress,
    String? masterId,
    List<_i10.ZoneMember>? members,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#createZone, [ipAddress, masterId, members]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> addZoneMembers(
    String? ipAddress,
    String? masterId,
    List<_i10.ZoneMember>? members,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#addZoneMembers, [ipAddress, masterId, members]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> removeZoneMembers(
    String? ipAddress,
    String? masterId,
    List<_i10.ZoneMember>? members,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#removeZoneMembers, [
              ipAddress,
              masterId,
              members,
            ]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> userPlayControl(String? ipAddress, String? controlType) =>
      (super.noSuchMethod(
            Invocation.method(#userPlayControl, [ipAddress, controlType]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<List<_i11.Preset>> getPresets(String? ipAddress) =>
      (super.noSuchMethod(
            Invocation.method(#getPresets, [ipAddress]),
            returnValue: _i9.Future<List<_i11.Preset>>.value(<_i11.Preset>[]),
          )
          as _i9.Future<List<_i11.Preset>>);

  @override
  _i9.Future<List<_i12.Recent>> getRecents(String? ipAddress) =>
      (super.noSuchMethod(
            Invocation.method(#getRecents, [ipAddress]),
            returnValue: _i9.Future<List<_i12.Recent>>.value(<_i12.Recent>[]),
          )
          as _i9.Future<List<_i12.Recent>>);

  @override
  _i9.Future<List<_i11.Preset>> removePreset(
    String? ipAddress,
    String? presetId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#removePreset, [ipAddress, presetId]),
            returnValue: _i9.Future<List<_i11.Preset>>.value(<_i11.Preset>[]),
          )
          as _i9.Future<List<_i11.Preset>>);

  @override
  _i9.Future<void> standby(String? ipAddress) =>
      (super.noSuchMethod(
            Invocation.method(#standby, [ipAddress]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<List<_i11.Preset>> storePreset(
    String? ipAddress,
    String? presetId,
    String? spotifyUri,
    String? spotifyUserId,
    String? itemName,
    String? containerArt,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#storePreset, [
              ipAddress,
              presetId,
              spotifyUri,
              spotifyUserId,
              itemName,
              containerArt,
            ]),
            returnValue: _i9.Future<List<_i11.Preset>>.value(<_i11.Preset>[]),
          )
          as _i9.Future<List<_i11.Preset>>);

  @override
  _i9.Future<List<_i11.Preset>> storeTuneInPreset(
    String? ipAddress,
    String? presetId,
    String? stationId,
    String? itemName,
    String? containerArt,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#storeTuneInPreset, [
              ipAddress,
              presetId,
              stationId,
              itemName,
              containerArt,
            ]),
            returnValue: _i9.Future<List<_i11.Preset>>.value(<_i11.Preset>[]),
          )
          as _i9.Future<List<_i11.Preset>>);

  @override
  _i9.Future<List<_i11.Preset>> storeInternetRadioPreset(
    String? ipAddress,
    String? presetId,
    String? url,
    String? itemName,
    String? containerArt,
    String? apiUrl,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#storeInternetRadioPreset, [
              ipAddress,
              presetId,
              url,
              itemName,
              containerArt,
              apiUrl,
            ]),
            returnValue: _i9.Future<List<_i11.Preset>>.value(<_i11.Preset>[]),
          )
          as _i9.Future<List<_i11.Preset>>);

  @override
  _i9.Future<void> sendKey(
    String? ipAddress,
    String? keyValue,
    String? state,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#sendKey, [ipAddress, keyValue, state]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> setSpeakerName(String? ipAddress, String? name) =>
      (super.noSuchMethod(
            Invocation.method(#setSpeakerName, [ipAddress, name]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> selectContentItem(String? ipAddress, _i12.Recent? recent) =>
      (super.noSuchMethod(
            Invocation.method(#selectContentItem, [ipAddress, recent]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> selectPreset(String? ipAddress, _i11.Preset? preset) =>
      (super.noSuchMethod(
            Invocation.method(#selectPreset, [ipAddress, preset]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<int> getLanguage(String? ipAddress) =>
      (super.noSuchMethod(
            Invocation.method(#getLanguage, [ipAddress]),
            returnValue: _i9.Future<int>.value(0),
          )
          as _i9.Future<int>);

  @override
  _i9.Future<_i6.BassCapabilities> getBassCapabilities(String? ipAddress) =>
      (super.noSuchMethod(
            Invocation.method(#getBassCapabilities, [ipAddress]),
            returnValue: _i9.Future<_i6.BassCapabilities>.value(
              _FakeBassCapabilities_5(
                this,
                Invocation.method(#getBassCapabilities, [ipAddress]),
              ),
            ),
          )
          as _i9.Future<_i6.BassCapabilities>);

  @override
  _i9.Future<_i6.Bass> getBass(String? ipAddress) =>
      (super.noSuchMethod(
            Invocation.method(#getBass, [ipAddress]),
            returnValue: _i9.Future<_i6.Bass>.value(
              _FakeBass_6(this, Invocation.method(#getBass, [ipAddress])),
            ),
          )
          as _i9.Future<_i6.Bass>);

  @override
  _i9.Future<void> setBass(String? ipAddress, int? bass) =>
      (super.noSuchMethod(
            Invocation.method(#setBass, [ipAddress, bass]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> setLanguage(String? ipAddress, int? languageCode) =>
      (super.noSuchMethod(
            Invocation.method(#setLanguage, [ipAddress, languageCode]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<bool> isClockDisplaySupported(String? ipAddress) =>
      (super.noSuchMethod(
            Invocation.method(#isClockDisplaySupported, [ipAddress]),
            returnValue: _i9.Future<bool>.value(false),
          )
          as _i9.Future<bool>);

  @override
  _i9.Future<_i7.ClockConfig> getClockDisplay(String? ipAddress) =>
      (super.noSuchMethod(
            Invocation.method(#getClockDisplay, [ipAddress]),
            returnValue: _i9.Future<_i7.ClockConfig>.value(
              _FakeClockConfig_7(
                this,
                Invocation.method(#getClockDisplay, [ipAddress]),
              ),
            ),
          )
          as _i9.Future<_i7.ClockConfig>);

  @override
  _i9.Future<void> setClockDisplay(
    String? ipAddress,
    _i7.ClockConfig? config,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#setClockDisplay, [ipAddress, config]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);
}
