// Mocks generated by Mockito 5.4.6 from annotations
// in ueberboese_app/test/pages/edit_spotify_preset_page_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i5;
import 'package:ueberboese_app/models/spotify_account.dart' as _i6;
import 'package:ueberboese_app/models/spotify_entity.dart' as _i2;
import 'package:ueberboese_app/services/spotify_api_service.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeSpotifyEntity_0 extends _i1.SmartFake implements _i2.SpotifyEntity {
  _FakeSpotifyEntity_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [SpotifyApiService].
///
/// See the documentation for Mockito's code generation for more information.
class MockSpotifyApiService extends _i1.Mock implements _i3.SpotifyApiService {
  MockSpotifyApiService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<String> initSpotifyAuth(String? apiUrl) =>
      (super.noSuchMethod(
            Invocation.method(#initSpotifyAuth, [apiUrl]),
            returnValue: _i4.Future<String>.value(
              _i5.dummyValue<String>(
                this,
                Invocation.method(#initSpotifyAuth, [apiUrl]),
              ),
            ),
          )
          as _i4.Future<String>);

  @override
  _i4.Future<void> confirmSpotifyAuth(String? apiUrl, String? code) =>
      (super.noSuchMethod(
            Invocation.method(#confirmSpotifyAuth, [apiUrl, code]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<List<_i6.SpotifyAccount>> listSpotifyAccounts(String? apiUrl) =>
      (super.noSuchMethod(
            Invocation.method(#listSpotifyAccounts, [apiUrl]),
            returnValue: _i4.Future<List<_i6.SpotifyAccount>>.value(
              <_i6.SpotifyAccount>[],
            ),
          )
          as _i4.Future<List<_i6.SpotifyAccount>>);

  @override
  _i4.Future<_i2.SpotifyEntity> getSpotifyEntity(
    String? apiUrl,
    String? spotifyUri,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getSpotifyEntity, [apiUrl, spotifyUri]),
            returnValue: _i4.Future<_i2.SpotifyEntity>.value(
              _FakeSpotifyEntity_0(
                this,
                Invocation.method(#getSpotifyEntity, [apiUrl, spotifyUri]),
              ),
            ),
          )
          as _i4.Future<_i2.SpotifyEntity>);
}
