name: ueberboese_app
description: "ueberboese app"
publish_to: "none"
version: 0.41.0+44

environment:
  sdk: ^3.12.1
  flutter: 3.44.8

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.5+1
  http: ^1.6.0
  xml: ^7.0.1
  shared_preferences: ^2.5.4
  url_launcher: ^6.3.2
  package_info_plus: ^10.2.0
  app_links: ^7.1.1
  intl: ^0.20.2
  web_socket_channel: ^3.0.3
  udp: ^5.0.3
  font_awesome_flutter: ^11.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  mockito: ^5.7.0
  build_runner: ^2.11.0
  flutter_launcher_icons: 0.14.4

flutter:
  uses-material-design: true

flutter_launcher_icons:
  android: true
  min_sdk_android: 21
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/icon/app_icon.png"
  adaptive_icon_monochrome: "assets/icon/app_icon.png"
  ios: false
  remove_alpha_ios: true
  background_color_ios: "#ffffff"
  linux:
    generate: true
  macos:
    generate: true
  windows:
    generate: true
    icon_size: 256
  image_path: "assets/icon/app_icon.png"
